name: Android Tests

on:
  push:
    branches:
      - master
      - home
  pull_request:
    branches:
      - master
      - home

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

# Instala o Android SDK e adb
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        licenses: | # Aceita licenças do SDK
          android-sdk-license-5be876d5
          android-sdk-license-2742d5c5

    # Adiciona o Android SDK Platform-Tools ao PATH
    - name: Add adb to PATH
      run: |
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

    # Configura o emulador com target válido
    - name: Run tests on emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis  # ✅ Valor válido (com Google APIs)
        profile: Pixel 6
        arch: x86_64
        script: ./gradlew connectedDebugAndroidTest

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build --warning-mode all

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-${{ runner.os }}-
          

    - name: Run unit tests
      run: ./gradlew test

    - name: Run instrumented tests
      run: ./gradlew connectedAndroidTest
